// Stage 5 — write the canonical lichess.json into data/puzzles/ + attribution.
//
// Reads selection.json directly. If explained.json exists alongside it
// (from a prior `explain` run), merges in the explanation/hints fields;
// otherwise emits the raw schema and lets the puzzle UI fall back to
// engine-only feedback.

import { mkdir, readFile, writeFile, stat } from 'node:fs/promises'
import {
  EXPLAINED_JSON,
  LICHESS_OUT,
  LICHESS_README,
  OUTPUT_DIR,
  SELECTION_JSON,
} from './paths.js'
import type { FilteredEntry, OutPuzzle } from './types.js'

interface ExplainedEntry extends FilteredEntry {
  explanation: string
  hints: [string, string, string]
}

const LEGENDS_MIN_RATING = 3000

export async function runEmit(): Promise<void> {
  const selection: FilteredEntry[] = JSON.parse(await readFile(SELECTION_JSON, 'utf8'))
  const explanationMap = await loadExplanations()
  await mkdir(OUTPUT_DIR, { recursive: true })

  const puzzles: OutPuzzle[] = selection.map((e) => {
    const explained = explanationMap.get(e.puzzleId)
    return {
      id: `lichess-${e.puzzleId}`,
      fen: e.fenAfterSetup,
      sideToMove: e.sideToMove,
      solution: e.solution,
      motifs: dedupeMotifs([e.primaryMotif, ...e.themes]),
      plot: e.plot,
      difficulty: e.rating,
      ratingDeviation: e.ratingDeviation,
      legends: e.rating >= LEGENDS_MIN_RATING,
      source: {
        provider: 'lichess',
        puzzleId: e.puzzleId,
        license: 'CC0',
      },
      ...(explained ? { explanation: explained.explanation, hints: explained.hints } : {}),
    }
  })

  // Sort easiest first overall — within a plot the per-puzzle server will
  // pick by rating anyway, so the file order is just for human inspection.
  puzzles.sort((a, b) => a.difficulty - b.difficulty)

  await writeFile(LICHESS_OUT, JSON.stringify(puzzles, null, 2))
  console.log(`Wrote ${puzzles.length} puzzles → ${LICHESS_OUT}`)

  await writeFile(LICHESS_README, README_TEXT.trim() + '\n')
  console.log(`Wrote attribution → ${LICHESS_README}`)
}

async function loadExplanations(): Promise<Map<string, ExplainedEntry>> {
  try {
    await stat(EXPLAINED_JSON)
  } catch {
    console.log('  (no explained.json — emitting puzzles without explanations)')
    return new Map()
  }
  const arr: ExplainedEntry[] = JSON.parse(await readFile(EXPLAINED_JSON, 'utf8'))
  console.log(`  Merging ${arr.length} explanations from explained.json`)
  return new Map(arr.map((e) => [e.puzzleId, e]))
}

function dedupeMotifs(arr: string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const m of arr) {
    if (!seen.has(m)) {
      seen.add(m)
      out.push(m)
    }
  }
  return out
}

const README_TEXT = `
# Lichess Puzzles

The puzzles in \`lichess.json\` are derived from the
[Lichess open puzzle database](https://database.lichess.org/#puzzles), licensed
under CC0 1.0 Universal (public domain dedication).

## Provenance

Each entry preserves \`source.puzzleId\`, which is the original Lichess id.
You can look up any puzzle on Lichess at
\`https://lichess.org/training/<puzzleId>\`.

The position FEN we store is the position **after** the opponent's setup
move has been played — that is, the puzzle's "your turn" starting point.
The original Lichess CSV stores the FEN before that setup move; the
pipeline (\`tools/puzzle-import\`) handles the conversion.

## Pipeline

Re-generate with:

\`\`\`bash
pnpm --filter @power-up-chess/puzzle-import all
\`\`\`

Stages: fetch → filter → sample → emit → upload. The optional \`explain\`
stage (\`pnpm --filter @power-up-chess/puzzle-import explain\`) generates
per-puzzle explanations + hints via Gemini and is rerun on demand because
it's expensive at 5,000+ puzzles. See \`tools/puzzle-import/src/cli.ts\`.

## Schema

Each puzzle carries:

- \`plot\`: one of \`mate\`, \`fork\`, \`pinSkewer\`, \`sacrifice\`, \`endgame\`, \`defense\`
- \`difficulty\`: Lichess Glicko rating (400-3000 main band, 3000+ Legends)
- \`ratingDeviation\`: confidence on that rating
- \`legends: true\` for the 100 Legends Hall puzzles
- \`source.puzzleId\`: original Lichess id, CC0
- \`explanation\` / \`hints\`: optional editorial layer (Lucy host voice)

## Editorial layer

When present, \`explanation\` and \`hints\` are generated by Gemini 3.5
Flash using the Lucy host persona. They are original child-facing text
written for this project — they are not derived from any third-party
commentary in the Lichess dataset.
`
