// Stage 5 — write the canonical lichess.json into data/puzzles/ + attribution.

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { EXPLAINED_JSON, LICHESS_OUT, LICHESS_README, OUTPUT_DIR } from './paths.js'
import type { FilteredEntry, OutPuzzle } from './types.js'

interface ExplainedEntry extends FilteredEntry {
  explanation: string
  hints: [string, string, string]
}

export async function runEmit(): Promise<void> {
  const explained: ExplainedEntry[] = JSON.parse(await readFile(EXPLAINED_JSON, 'utf8'))
  await mkdir(OUTPUT_DIR, { recursive: true })

  const puzzles: OutPuzzle[] = explained.map((e) => ({
    id: `lichess-${e.puzzleId}`,
    fen: e.fenAfterSetup,
    sideToMove: e.sideToMove,
    solution: e.solution,
    motifs: dedupeMotifs([e.primaryMotif, ...e.themes]),
    difficulty: e.rating,
    source: {
      provider: 'lichess',
      puzzleId: e.puzzleId,
      license: 'CC0',
    },
    explanation: e.explanation,
    hints: e.hints,
  }))

  // Sort: easiest first within each primary motif group, motif order
  // matches our garden grouping in the web app.
  puzzles.sort((a, b) => a.difficulty - b.difficulty)

  await writeFile(LICHESS_OUT, JSON.stringify(puzzles, null, 2))
  console.log(`Wrote ${puzzles.length} puzzles → ${LICHESS_OUT}`)

  await writeFile(LICHESS_README, README_TEXT.trim() + '\n')
  console.log(`Wrote attribution → ${LICHESS_README}`)
}

function dedupeMotifs(arr: string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const m of arr) {
    if (!seen.has(m)) {
      seen.add(m)
      out.push(m)
    }
  }
  return out
}

const README_TEXT = `
# Lichess Puzzles

The puzzles in \`lichess.json\` are derived from the
[Lichess open puzzle database](https://database.lichess.org/#puzzles), licensed
under CC0 1.0 Universal (public domain dedication).

## Provenance

Each entry preserves \`source.puzzleId\`, which is the original Lichess id.
You can look up any puzzle on Lichess at
\`https://lichess.org/training/<puzzleId>\`.

The position FEN we store is the position **after** the opponent's setup
move has been played — that is, the puzzle's "your turn" starting point.
The original Lichess CSV stores the FEN before that setup move; the
pipeline (\`tools/puzzle-import\`) handles the conversion.

## Pipeline

Re-generate with:

\`\`\`bash
export GEMINI_API_KEY=...    # or rely on firebase functions:secrets:access
pnpm --filter @power-up-chess/puzzle-import start
\`\`\`

Stages: fetch → filter → sample → explain → emit. See
\`tools/puzzle-import/src/cli.ts\`.

## Editorial layer

\`explanation\` and \`hints\` for each puzzle were generated by Gemini 3.5
Flash using the Lucy host persona. They are original child-facing text
written for this project — they are not derived from any third-party
commentary in the Lichess dataset.
`
