// Stage 5 — write `data/stories/{storyId}.json` per validated story plus
// a manifest + README. Rights metadata is attached but every story is
// initially marked `engineering-stored-not-reviewed`; the user owns the
// rights review pass (see CLAUDE.md / MVP2_PLAN §6.5).

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { BOOKS } from './books.js'
import { STORIES_MANIFEST, STORIES_OUT_DIR, STORIES_README, VALIDATED_JSON } from './paths.js'
import type { EmittedStory, VoicedStory } from './types.js'

export async function runEmit(): Promise<void> {
  await mkdir(STORIES_OUT_DIR, { recursive: true })

  const validated: VoicedStory[] = JSON.parse(await readFile(VALIDATED_JSON, 'utf8'))
  const bookById = new Map(BOOKS.map((b) => [b.bookId, b]))
  const now = Date.now()

  const manifest: Array<{ id: string; bookId: string; title: string; motif: string; era?: string }> = []

  for (const s of validated) {
    const book = bookById.get(s.bookId)
    const emitted: EmittedStory = {
      ...s,
      source: {
        book: book?.title ?? s.bookId,
        author: book?.author,
        year: book?.year,
        page: s.sourcePage,
      },
      rightsStatus: 'engineering-stored-not-reviewed',
      generatedAt: now,
    }
    await writeFile(`${STORIES_OUT_DIR}/${s.id}.json`, JSON.stringify(emitted, null, 2))
    manifest.push({ id: s.id, bookId: s.bookId, title: s.title, motif: s.motif, era: s.era })
  }

  await writeFile(STORIES_MANIFEST, JSON.stringify({ count: manifest.length, generatedAt: now, stories: manifest }, null, 2))
  await writeFile(STORIES_README, buildReadme(validated.length))
  console.log(`Wrote ${validated.length} stories → ${STORIES_OUT_DIR}`)
}

function buildReadme(count: number): string {
  const bookList = BOOKS.map((b) => `- **${b.title}** — ${b.author ?? 'author unknown'}${b.year ? ` (${b.year})` : ''}`).join('\n')
  return `# Story Bank

Last generated by \`tools/story-import\`.

${count} stories currently published in this directory, plus a manifest.

## Source books

${bookList}

## Pipeline + rights

Stories are extracted offline from the books in
\`docs/books_and_references/\` (git-ignored) by the pipeline in
\`tools/story-import/\`. Each story is original-wording retold by an LLM;
the pipeline includes an anti-verbatim check (≥30 char overlap with the
source rejects the candidate). Every emitted story carries:

- \`source\`: book title, author, year, page range.
- \`rightsStatus\`: starts at \`engineering-stored-not-reviewed\`. The user
  owns rights review; engineering stores the field but does not gate on
  it.
- \`variants.lucy\` and \`variants.luca\`: ready-to-read host-voiced
  retellings.

To regenerate:

\`\`\`sh
GEMINI_API_KEY=... pnpm --filter @power-up-chess/story-import all
\`\`\`

## Conventions

- Story id is \`{bookId}-{slug}\` (slug derived from the original title).
- One JSON file per story; small enough to ship in the deploy bundle.
- \`manifest.json\` is the index loaded by the Hall to pick a random story.
`
}
